# Generated by Django 3.2.20 on 2023-07-15 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название застройщика')),
            ],
            options={
                'verbose_name': 'Застройщик',
                'verbose_name_plural': 'Застройщики',
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название ЖК')),
                ('url', models.URLField(unique=True, verbose_name='Ссылка')),
                ('square', models.FloatField(verbose_name='Площадь')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('date', models.DateField(verbose_name='Дата сдачи ЖК')),
                ('decor', models.BooleanField(verbose_name='Отделка')),
                ('date_view', models.DateField(auto_now_add=True, verbose_name='Дата просмотра')),
                ('is_metro', models.BooleanField(verbose_name='Наличие метро')),
                ('metro_name', models.CharField(blank=True, max_length=50, verbose_name='Название метро')),
                ('is_mcd', models.BooleanField(verbose_name='Наличие МЦД')),
                ('mcd_name', models.CharField(blank=True, max_length=50, verbose_name='Название МЦД')),
                ('rent', models.IntegerField(verbose_name='Плата за аренду')),
                ('mortgage', models.IntegerField(verbose_name='Ипотека')),
                ('development', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsing.development', verbose_name='Застройщик')),
            ],
            options={
                'verbose_name': 'Обьект',
                'verbose_name_plural': 'Обьекты',
            },
        ),
    ]
