# Generated by Django 3.2.20 on 2023-07-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название застройщика')),
            ],
            options={
                'verbose_name': 'Застройщики',
                'verbose_name_plural': 'Застройщики',
            },
        ),
        migrations.AlterModelOptions(
            name='apartment',
            options={'verbose_name': 'Обьекты', 'verbose_name_plural': 'Обьекты'},
        ),
        migrations.AlterField(
            model_name='apartment',
            name='date',
            field=models.DateField(verbose_name='Дата сдачи ЖК'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='date_view',
            field=models.DateField(verbose_name='Дата просмотра'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='decor',
            field=models.BooleanField(verbose_name='Отделка'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='is_mcd',
            field=models.BooleanField(verbose_name='Наличие МЦД'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='is_metro',
            field=models.BooleanField(verbose_name='Наличие метро'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='mcd_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название МЦД'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='metro_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название метро'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='mortgage',
            field=models.IntegerField(verbose_name='Ипотека'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название ЖК'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='rent',
            field=models.IntegerField(verbose_name='Плата за аренду'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='square',
            field=models.FloatField(verbose_name='Площадь'),
        ),
    ]
