# Generated by Django 3.2.20 on 2023-07-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0002_apartment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='image1',
            field=models.CharField(blank=True, max_length=80, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image',
            field=models.FilePathField(path='F:/github/bazParsing/bazParsing/static/images/parsing/'),
        ),
    ]
