# Generated by Django 3.2.20 on 2023-07-10 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0003_site'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Сайты', 'verbose_name_plural': 'Сайты'},
        ),
        migrations.AddField(
            model_name='site',
            name='development',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsing.development', verbose_name='Застройщик'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='date_view',
            field=models.DateField(auto_now_add=True, verbose_name='Дата просмотра'),
        ),
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
