# Generated by Django 3.2.20 on 2023-07-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0003_auto_20230716_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='image1',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image',
            field=models.FilePathField(path='F:/github/bazParsing/bazParsing/static/images/parsing/', verbose_name='Изображение'),
        ),
    ]
