# Generated by Django 3.2.20 on 2023-07-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0004_auto_20230716_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='image',
            field=models.FilePathField(path='F:/github/bazParsing/bazParsing/media/images/parsing/', verbose_name='Изображение'),
        ),
    ]
