# Generated by Django 3.2.20 on 2023-07-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0005_alter_apartment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='image',
            field=models.FilePathField(path='F:/github/bazParsing/bazParsing/media/', verbose_name='Изображение'),
        ),
    ]
