# Generated by Django 4.2.3 on 2023-07-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0006_alter_apartment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='image',
            field=models.FilePathField(path='C:/', verbose_name='Изображение'),
        ),
    ]
