# Generated by Django 4.2.3 on 2023-07-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0007_alter_apartment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='image',
            field=models.ImageField(upload_to='apartmentimg', verbose_name='Изображение'),
        ),
    ]
