# Generated by Django 4.2.3 on 2023-07-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0008_alter_apartment_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentialArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название ЖК')),
                ('date', models.CharField(max_length=25, verbose_name='Дата сдачи ЖК')),
                ('price', models.CharField(max_length=25, verbose_name='Цена')),
                ('metro_name', models.CharField(max_length=50, verbose_name='Название метро')),
                ('road_time', models.CharField(max_length=50, verbose_name='Время до метро')),
            ],
            options={
                'verbose_name': 'Жилой комплекс',
                'verbose_name_plural': 'Жилые комплексы',
            },
        ),
    ]
